### ISSUE TITLE
[BUG]1.35在Windows客户端上弹幕加载成功但不显示

### ISSUE THREAD

**Issue by SakuraMio2006** [chen3861229/dd-danmaku#10]
弹幕加载正常，但是不显示，暂停再继续播放后正常显示
弹幕关闭再开启同样不显示，暂停再继续播放后正常显示
把
`_media.src = ''; // !!! IOS 上此属性必须存在,否则 currentTime = 0 无法更新`
这一行注释掉之后就正常了

**Comment by chen3861229** [comment]
嗯，这个已经修复了，重发了一遍 1.35
https://github.com/chen3861229/dd-danmaku/releases/tag/1.35
