### ISSUE TITLE
[BUG] 匹配规则写法

### ISSUE THREAD

**Issue by Jisxu** [chen3861229/dd-danmaku#12]
// @match        */web/index.html
// @match        */web/

match规则能否写成标准格式
// @match        \*://\*/web/index.html
// @match        \*://\*/web/

我这边篡改猴匹配比较宽松，暴力猴比较严格，只有下面这种标准格式才能匹配上

**Comment by chen3861229** [comment]
嗯，没问题，精确点儿是更好的，已提交，e7bc0c051e5d960f9aea566f23246feceedb650f，不过估计得等段时间再发版了，如果有其他修复，也欢迎 pr
