### ISSUE TITLE
[BUG]从1.33以后版本增加第三方弹幕源不会加载、

### ISSUE THREAD

**Issue by Awhitedressy** [chen3861229/dd-danmaku#18]
![image](https://github.com/user-attachments/assets/4159f29f-49ca-40b3-9ee3-4f769ed812ac)
![image](https://github.com/user-attachments/assets/48eeb359-635c-4370-a987-f959a2d6c3e9)
这是1.37版本的错误。

![image](https://github.com/user-attachments/assets/8fdffe58-f348-497f-984e-471c233cac54)
![image](https://github.com/user-attachments/assets/ee6cc179-f7ad-4a29-aeb6-5bf1f2fe6769)

1.33版本可以正常加载。
js我装在emby 的cssjs插件。
目前用的是1.33版本

**Comment by chen3861229** [comment]
已修复，https://github.com/chen3861229/dd-danmaku/releases/tag/1.38
