### ISSUE TITLE
能否加一个屏蔽滚动弹幕的功能，大佬，球球了

### ISSUE THREAD

**Issue by ailachan** [chen3861229/dd-danmaku#30]

**Comment by chen3861229** [comment]
啊？是指，从右至左，从左至右，这两种类型吗？

**Comment by chen3861229** [comment]
已添加，不过暂时在develop分支，
https://cdn.jsdelivr.net/gh/chen3861229/dd-danmaku@develop/ede.js

https://github.com/chen3861229/dd-danmaku/commit/be7198aeb3c699169de02d039cc3aa524e141c81

**Comment by ailachan** [comment]
> 啊？是指，从右至左，从左至右，这两种类型吗？

对的

**Comment by ailachan** [comment]
> 已添加，不过暂时在develop分支， https://cdn.jsdelivr.net/gh/chen3861229/dd-danmaku@develop/ede.js
> 
> [be7198a](https://github.com/chen3861229/dd-danmaku/commit/be7198aeb3c699169de02d039cc3aa524e141c81)

好的
