### ISSUE TITLE
上游danmaku.js的改进

### ISSUE THREAD

**Issue by lanytcc** [chen3861229/dd-danmaku#6]
danmaku.js的弹幕位置计算方式会导致滚动弹幕大量重叠，很影响观看体验。

我正好有这方面经验，所以昨天fork了 danmaku.js 做了一些修改。

查看https://github.com/lanytcc/Danmaku

或者使用`https://cdn.jsdelivr.net/gh/lanytcc/Danmaku@v1.1.0/dist/danmaku.min.js`

你可以做一些测试，或者直接使用`<script src="https://cdn.jsdelivr.net/gh/lanytcc/Danmaku@v1.1.0/dist/danmaku.min.js"></script> <script src="https://cdn.jsdelivr.net/gh/lanytcc/dd-danmaku@v1.0.0/ede.min.js" defer></script>` 来载入看看。

本仓库的fork我只添加了一个ede.min.js，方便不修改载入，如果你需要的话我可以提交pr

![图片](https://github.com/user-attachments/assets/b097ee30-e854-4c88-98b4-d6d70343f9ab)

**Comment by chen3861229** [comment]
1.多谢对于业务功能的原生 css 及 js 优化，这块对于我们一些后端开发来讲，不是太熟，帮大忙了

2.这里记录下变更版本，https://github.com/lanytcc/dd-danmaku/releases/tag/v1.0.0 基于上游库https://github.com/weizhenye/Danmaku/releases/tag/v2.0.6 修复了`弹幕位置计算方式会导致滚动弹幕大量重叠`的问题

3.上游库作者 @weizhenye 查看 issus 判断出应该还是活跃状态的，建议将上述优化 pr 过去，这样可能方便原上游库的一些后续优化

4.然后未合并前，此仓库的话，前端写得太乱了，应该不太可能被其他库所依赖了，所以会将内置`<script src="https://cdn.jsdelivr.net/gh/lanytcc/Danmaku@v1.1.0/dist/danmaku.min.js">`这个版本的上游库作为默认依赖，不过前提是此仓库中的原始上游库版本没变更的话，`https://github.com/weizhenye/Danmaku/releases/tag/v2.0.6`

5.`<script src="https://cdn.jsdelivr.net/gh/lanytcc/dd-danmaku@v1.0.0/ede.min.js" defer></script>`这个的话，也是因为此仓库前端写得不太规范，加上一些维护成本，所以个人倾向于没做`releases`的管理，不过这样带来了几个风险，我这边可能会频繁变更版本且无历史发行做稳定版回退，然后这个`ede.min.js`也属于修改后实时变化了，我找找看实时生成这个的插件，关于本仓库的一些修改的话，也欢迎 PR

**Comment by lanytcc** [comment]
1. 对于第3点，因为想要改动不影响其他功能，我还得继续做其他测试。目前在emby上的需求是够了的，所以暂时可以先用这个。
2. 关于4/5两点，我会尝试帮忙维护

另外，我也不是专业前端的，恰好以前给有类似的弹幕场景的开源软件提过PR：https://github.com/xfangfang/wiliwili

:)

**Comment by chen3861229** [comment]
1.我这边和朋友简单测试了下，没影响业务功能的正常使用，不过样式方面存在一个小问题，这个可能是原始上游库本身存在的，https://github.com/weizhenye/Danmaku/issues/55 ，我这边手机`120 fps`和电脑`240 fps`下是不存在抖动问题的，只在朋友那边`60 fps`显示器上存在，`canvas/dom`都存在`从左至右/从右至左`弹幕在`X轴`方向上的一个前后范围抖动问题，幅度很微小，大致就是原作者提到的`.5`这个数值大小，已测试 fork 前后，按原作者提到的移除`+.5|0`也没有变化，这个可能不是太好修

2.多谢帮忙维护了

**Comment by lanytcc** [comment]
是的，我在我的macbook上也观察到这个问题了，高刷反而没问题

我会重点关注这个问题

**Comment by weizhenye** [comment]
> danmaku.js的弹幕位置计算方式会导致滚动弹幕大量重叠

这个是指超出一屏后取模导致的重叠，还是未超出一屏就会重叠？前者是有意设计的，后者的话是 bug，可以提供下复现数据来提个 issue

**Comment by weizhenye** [comment]
抖动问题印象中有两三个 issue 提过，但都没有提供足够的信息，现在提到的 60 fps 有问题，我自己是没复现过的。

如果能提供复现的数据和 fps，我可以具体看下。

**Comment by lanytcc** [comment]
> > danmaku.js的弹幕位置计算方式会导致滚动弹幕大量重叠
> 
> 这个是指超出一屏后取模导致的重叠，还是未超出一屏就会重叠？前者是有意设计的，后者的话是 bug，可以提供下复现数据来提个 issue

指的前者，我猜到是这么设计的了，所以我没给你提issue。

**Comment by lanytcc** [comment]
> 抖动问题印象中有两三个 issue 提过，但都没有提供足够的信息，现在提到的 60 fps 有问题，我自己是没复现过的。
> 
> 如果能提供复现的数据和 fps，我可以具体看下。

确实有这个问题，我刚在排查，稍等

**Comment by lanytcc** [comment]
> > 抖动问题印象中有两三个 issue 提过，但都没有提供足够的信息，现在提到的 60 fps 有问题，我自己是没复现过的。
> > 如果能提供复现的数据和 fps，我可以具体看下。
> 
> 确实有这个问题，我刚在排查，稍等

@chen3861229 问题已经解决，使用`Danmaku@v1.1.0-t`版本的试试看，在我这已经正常了

**Comment by ykchenc** [comment]
1、`弹幕位置计算方式会导致滚动弹幕大量重叠`更改前后对比
更改前：https://github.com/weizhenye/Danmaku/releases/tag/v2.0.6
![1](https://github.com/user-attachments/assets/51323ab9-98b8-4453-afc3-d0ff55c966bf)
更改后：https://github.com/lanytcc/dd-danmaku/releases/tag/v1.0.0 
![2](https://github.com/user-attachments/assets/c68190e8-7d8d-47a3-bdcb-670ec02d0a04)

2、弹幕抖动效果，以下为桌面75fps、录屏软件60fps录制环境下复现效果
媒体名: 败犬女主太多了！
分集名: 第1话 专业青梅竹马八奈见杏菜的败相
弹幕来源：https://ddplay-api.7o7o.cc/cors/https://api.dandanplay.net/api/v2/comment/183170001?withRelated=true&chConvert=1
复现视频地址：https://tmp.link/f/66ec638c4cc60

**Comment by chen3861229** [comment]
@lanytcc 多谢，幸苦了，已在朋友机器上测试了，`Danmaku@v1.1.0-t`版本已经修复了，`弹幕位置计算方式会导致滚动弹幕大量重叠`和`低帧率下的弹幕微抖动`问题

@weizhenye 多谢原作者热心关注问题了

**Comment by lanytcc** [comment]
> @lanytcc 多谢，幸苦了，已在朋友机器上测试了，`Danmaku@v1.1.0-t`版本已经修复了，`弹幕位置计算方式会导致滚动弹幕大量重叠`和`低帧率下的弹幕微抖动`问题，[d2ddb77](https://github.com/chen3861229/dd-danmaku/commit/d2ddb77ae5ad5d652c22de3aba7a07ece40bfb57)
> 
> @weizhenye 多谢原作者热心关注问题了

我将tag设为1.2.0，并且补上了一个参数，没补之前显示osd栏时弹幕还是有点卡顿

**Comment by lanytcc** [comment]
@ykchenc 尝试使用Danmaku@v1.2.0，我这里测试已经非常丝滑:)

**Comment by weizhenye** [comment]
看上面截图，弹幕重叠确实改善了很多。

https://github.com/lanytcc/Danmaku 的改动有点多，我还没看具体逻辑，从原理上说，在保证每一条弹幕都准时出现的前提下，现有逻辑是贪心算法，应该已经是最「紧凑」的了，如果要达到上面截图的效果，我能想到的方法是弹幕不再准时出现，超出一屏的弹幕允许延时到紧跟已有弹幕的后面。但允许延时的话就会有极端场景导致延时很久，影响后续的弹幕。

目前这个改动的大致逻辑是怎样的？

**Comment by lanytcc** [comment]
> 看上面截图，弹幕重叠确实改善了很多。
> 
> https://github.com/lanytcc/Danmaku 的改动有点多，我还没看具体逻辑，从原理上说，在保证每一条弹幕都准时出现的前提下，现有逻辑是贪心算法，应该已经是最「紧凑」的了，如果要达到上面截图的效果，我能想到的方法是弹幕不再准时出现，超出一屏的弹幕允许延时到紧跟已有弹幕的后面。但允许延时的话就会有极端场景导致延时很久，影响后续的弹幕。
> 
> 目前这个改动的大致逻辑是怎样的？

根据高度和字体高度算出“固定轨道”，然后每次只需要维护一个轨道数组，在其中保留该最后一个弹幕的信息。

具体除了时间以外，还要计算“到达时间”，即一条弹幕走完全程的时间，以此来避免“追尾”。

至于延时，我这里没有做，找不到空就被丢掉不展示了，毕竟弹幕是时效性很强的东西（这里倒是可以做优先级展示，但是不好做判断就没做）。

我之前在为wiliwili编写直播弹幕功能时候，选择的是维护一个固定长度的双端队列，超出长度的弹幕会被丢弃，用来应对弹幕激增的场景

我这里在这改动是要跟emby配合，因为我要“看”弹幕，所以要解决重叠问题。如果“重叠”是feature的话，我觉得倒是可以不修改，因为也有需要展示弹幕“多”而非注重看的场景

如果你需要的话，我倒是可以整理整理提个pr

---

另外提一嘴，我今天（应该是昨天了，通宵看番去了:(。）我弄了个pixi.js 做渲染引擎，在win上的firefox引擎提升很大（win上Firefox的canvas渲染不行），而且在我的mac上功耗我没做严谨测试，功耗应该要小一点，这个我也可以提个pr过来，为了方便在别的设备测试还弄了个网页：https://demo.lanyt.cc/djs-benckmark.html

结果这玩意除了我说的那两个场景，其他貌似提升不大。。

**Comment by weizhenye** [comment]
看下来这个改动主要有两点差异：
1. 所有弹幕必须相同行高，才能固定轨道。原先是每条弹幕支持任意字号行高的。
2. 存在弹幕不展示。我更倾向于弹幕的过滤、限流等逻辑由开发者自行决策，是直接丢弃，还是像 B 站会把相同弹幕合并成 `谁问你了 x233` 这样减少弹幕数量，这个是开发者的业务逻辑相关了，弹幕库本身应该保持纯粹，给什么展示什么。

Danmaku 还是会保持现有逻辑，后续可能会看下延时的效果，增加配置延时的能力。

**Comment by lanytcc** [comment]
> 看下来这个改动主要有两点差异：
> 
>     1. 所有弹幕必须相同行高，才能固定轨道。原先是每条弹幕支持任意字号行高的。
> 
>     2. 存在弹幕不展示。我更倾向于弹幕的过滤、限流等逻辑由开发者自行决策，是直接丢弃，还是像 B 站会把相同弹幕合并成 `谁问你了 x233` 这样减少弹幕数量，这个是开发者的业务逻辑相关了，弹幕库本身应该保持纯粹，给什么展示什么。
> 
> 
> Danmaku 还是会保持现有逻辑，后续可能会看下延时的效果，增加配置延时的能力。

我也只是为了修改成更贴合我的需求，不过我尊重你的看法。方向上的不符合这也是我迟迟提issue的原因之一。

另外，我们在这个issue下面讨论的太久了，或许我们应该转到danmaku.js，或许接下来可以讨论一下pixi.js的问题。记得艾特我
