### ISSUE TITLE
大佬能否支持一下 自定义弹幕源 接口和dandanplay 是一样的

### ISSUE THREAD

**Issue by key762** [chen3861229/dd-danmaku#7]
大佬能否支持一下 自定义弹幕源 接口和dandanplay 是一样的，
https://hub.docker.com/repository/docker/anoraker/abetsy/general

**Comment by chen3861229** [comment]
`dandanplay`实时获取第三方网站弹幕，测试情况`2024.09.25`

01: 腾讯视频

黑执事 寄宿学校篇 第 01 话，未登录状态，非 VIP 独占，可实时获取解析后弹幕，且`网址`带不带`?`后参数无影响
https://v.qq.com/x/cover/mzc00200i0cs7p4/z4100z7alkc.html

黑执事 寄宿学校篇 第 09 话，未登录状态，该当前时间点为 VIP 独占，可实时获取解析后弹幕，且`网址`带不带`?`后参数无影响
https://v.qq.com/x/cover/mzc00200i0cs7p4/o4100tedqy6.html

02.爱奇艺视频

剧场版，灌篮高手 The First Slam Dunk，未登录状态，该当前时间点为 VIP 独占，可实时获取解析后弹幕，但需要注意网址不能带`?`后的参数，不然获取不到弹幕
https://www.iqiyi.com/v_1u6n00lesrg.html

03.优酷视频

一拳超人 第一季 第 01 话，未登录状态，该当前时间点为 VIP 独占，可实时获取解析后弹幕，且`网址`带不带`?`后参数无影响
https://v.youku.com/v_show/id_XMTM1MTc4MDU3Ng==.html?spm=a2hja.12701310.filter.25&s=0b39c5b6569311e5b2ad&s=0b39c5b6569311e5b2ad

04.Bilibili ，AcFun ...

这个之前测试过了，未登录状态，该当前时间点为 VIP 独占，可实时获取解析后弹幕，且`网址`带不带`?`后参数无影响
`dandanplay`原接口文档说明如下，
接口说明
此接口用于获取第三方弹幕站（如A/B/C站）上指定网址对应的弹幕。

05.芒果 TV

内地电视剧，长乐曲 第 2 集，未登录状态，该当前时间点为 VIP 独占，**无法获取**弹幕
https://www.mgtv.com/b/642790/21617783.html

间谍过家家 第一季 第 1 集，未登录状态，非 VIP 独占，**无法获取**弹幕
https://www.mgtv.com/b/666379/21630754.html

间谍过家家 第一季 第 2 集，未登录状态，该当前时间点为 VIP 独占，**无法获取**弹幕
https://www.mgtv.com/b/666379/21630755.html

综合上述测试结果，`dandanplay`接口除了`芒果 TV`无法解析，其余主流网站均可有效获取解析后弹幕内容，故不会再对接其他弹幕获取平台，抱歉了，毕竟可能涉及到一些弹幕内容结构的解析与转换过程，这个个人觉得还是`dandanplay`这种统一的`JSON`结构会比较方便，再加上`dandanplay`已经在弹幕领域耕耘十多年了，还是使用下它比较好，这样也方便后期添加发送弹幕的功能来完善弹幕的生态

**Comment by key762** [comment]
不是 只是允许自定义弹幕地址把接口前缀的https://api.dandanplay.net换成 http(s)://(你的服务器地址):(你的容器端口)/abetsy

主要是拓展弹幕的功能 虽然dandanplay可以实时获取第三方网站弹幕,但是谁也不想一集弄一下吧 换个客户端 历史记录都没

**Comment by key762** [comment]
只是个人见解哈 这个项目我开园出来了

**Comment by chen3861229** [comment]
好吧，这个简单，是我理解错了😅，之后这些脚本内的 API 地址将都可以在 UI 中进行手动填写

**Comment by chen3861229** [comment]
目前 1.34 之后的版本是可以在设置中自定义接口 URL 了

**Comment by shouwang0127** [comment]
大佬，我装了这个容器，自定义接口 URL具体要怎么设置呢？我在高级设置-自定义接口地址-获取指定弹幕库的所有弹幕，把默认的${dandanplayApi.prefix}替换为http(s)://(你的服务器地址):(你的容器端口)/abetsy不起作用

**Comment by key762** [comment]
> 大佬，我装了这个容器，自定义接口 URL具体要怎么设置呢？我在高级设置-自定义接口地址-获取指定弹幕库的所有弹幕，把默认的${dandanplayApi.prefix}替换为http(s)://(你的服务器地址):(你的容器端口)/abetsy不起作用

好像是dandanplay有更新，需要改代码

**Comment by A-Cepheus** [comment]
目前发现不是所有爱奇艺都能拉到弹幕，举例：https://www.iqiyi.com/v_1srlxwfjx0k.html
